import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:share_plus/share_plus.dart';

class ReportSharer {
  static Future<void> shareReportData({
    required DateTime date,
    required int plaquePercent,
    required String severity,
    required int score,
    required double confidence,
    required String recommendation,
    String? localImagePath,
    String? localPdfPath,
  }) async {
    final formattedDate =
        '${date.day} ${_monthName(date.month)}, ${date.year}';
    final confidencePct = (confidence * 100).round();

    final buffer = StringBuffer()
      ..writeln('🦷 PlaqueCheck AI Dental Diagnostic Report')
      ..writeln('----------------------------------------')
      ..writeln('📅 Date: $formattedDate')
      ..writeln('📊 Plaque Index: $plaquePercent% ($severity Risk)')
      ..writeln('🏆 Oral Health Score: $score / 100')
      ..writeln('🎯 AI Confidence: $confidencePct%')
      ..writeln()
      ..writeln('💡 Clinical Recommendation:')
      ..writeln(recommendation.isNotEmpty ? recommendation : 'Maintain regular brushing and oral care routine.')
      ..writeln()
      ..writeln('Generated by PlaqueCheck AI Engine');

    final textSummary = buffer.toString();

    try {
      final filesToShare = <XFile>[];

      if (localPdfPath != null && localPdfPath.isNotEmpty) {
        final pdfFile = File(localPdfPath);
        if (await pdfFile.exists()) {
          filesToShare.add(XFile(pdfFile.path, mimeType: 'application/pdf'));
        }
      }

      if (filesToShare.isEmpty && localImagePath != null && localImagePath.isNotEmpty) {
        final imgFile = File(localImagePath);
        if (await imgFile.exists()) {
          filesToShare.add(XFile(imgFile.path));
        }
      }

      if (filesToShare.isNotEmpty) {
        await Share.shareXFiles(
          filesToShare,
          text: textSummary,
          subject: 'PlaqueCheck AI Dental Report',
        );
      } else {
        await Share.share(
          textSummary,
          subject: 'PlaqueCheck AI Dental Report',
        );
      }
    } catch (e) {
      debugPrint('Share error: $e');
      // Fallback to plain text sharing
      await Share.share(
        textSummary,
        subject: 'PlaqueCheck AI Dental Report',
      );
    }
  }

  static String _monthName(int month) {
    const months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ];
    if (month >= 1 && month <= 12) {
      return months[month - 1];
    }
    return '';
  }
}
